name:                HoneyBadgerBFT
version:             0.1.0.0
github:              "https://github.com/bigchaindb/HoneyBadgerBFT"
author:              "Lev Berman"
maintainer:          "ldmberman@gmail.com"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/bigchaindb/HoneyBadgerBFT#readme

dependencies:
- base == 4.9.0.0
- reedsolomon == 0.0.4.3
- exceptions == 0.8.3
- bytestring == 0.10.8.1
- vector == 0.11.0.0
- merkle-tree == 0.1.0
- cereal == 0.5.3.0
- mtl == 2.2.1
- containers == 0.5.7.1

library:
  source-dirs: src

executables:
  HoneyBadgerBFT-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HoneyBadgerBFT

tests:
  HoneyBadgerBFT-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HoneyBadgerBFT
    - tasty
    - tasty-hunit
